version: "3.2"

services:
  bbot-bot:
    image: bbot-bot
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    env_file: .env

    command: npm run chat:production
